### ISSUE TITLE
help serving mbtiles

### ISSUE THREAD

**Issue by makella** [CartoDB/GoT#3]
@ivanmalagon 

As I showed a couple of weeks back, I have a local mbtiles file that contains all of the GoT basemap data.

In order to use this file, I need to host it somewhere... I've been reading through many different posts and a lot of them talk about using Docker. For example see the section "Provisioning a Server While Getting Everyone Dressed" here: https://www.axismaps.com/blog/2018/06/vector-tile-server/

I also think this is something we can host on our infrastructure, but not sure how to do that. Right now, that is the major blocker for me.

Any suggestions/ideas?

thanks!

**Comment by juanignaciosl** [comment]
This is over, isn't it?

**Comment by makella** [comment]
yep!
